### ISSUE TITLE
Edit local Markdown file in web browser while offline?

### ISSUE THREAD

**Issue by orschiro** [commenthol/md-fileserver#1]
Dear @commenthol,

I found your md-filesever and have a related question. 

Do you know of any way to edit local Markdown files in a web browser while offline?

Thank you!

**Comment by commenthol** [comment]
search for mado in apps on Chrome webstore. that should do.

**Comment by orschiro** [comment]
@commenthol thank you!

For future reference: 

https://chrome.google.com/webstore/detail/mado/gmmlaihnodfojphcmjeemhaeajaldcdj/related
