### ISSUE TITLE
Config.json and KaTex

### ISSUE THREAD

**Issue by JanosSarkoezi** [commenthol/md-fileserver#11]
This is more of a question than a issue.

Is there a way to define a configuration in the config.json file for KaTex?
I would like to define a macro for KaTex. The content of my config.json is
```json
{
  "updatedAt": "2021-08-21T08:17:39.482Z",
  "token": "xxx",
  "port": 4000,
  "filter": true,
  "confluencer": false,
  "confluenceHtml": false,
  "template": {
    "highlight": "github-dark"
  }
}

```

**Comment by commenthol** [comment]
Hi, 
the best option as of now would be the following:

1.  Clone this project and change directory
2.  Edit the `config.js` 
    ```js
    /// add `markdown-it` plugins
    markdownItPlugins: function (parser) {
      return parser
        .use(require('markdown-it-abbr'))
        ...
        .use(require('@commenthol/markdown-it-katex'), {
          // add here your kaTex options you'd like to have
          // See https://katex.org/docs/options.html
          // e.g.
          macros: {
            "\\RR": "\\mathbb{R}"
          }
        })
        .use(require('markdown-it-mark'))
        ...
    ```
3.  Install your changes globally with `npm i -g` from the cloned folder.
4.  Now running `mdstart` should include your katex options. 

I did not try this by myself, but i suppose that this should work.
