### ISSUE TITLE
Just a thank you

### ISSUE THREAD

**Issue by gtarsia** [commenthol/md-fileserver#14]
This project is very easy to setup and work with, it's not an extension for chrome or an editor, it's not a weird side by side web editor, it's not a bloated web framework just to see md files, it does one job and it does it well.

The formatting looks great, the pages render quickly, doesn't mess up with the scrolling when you change something, the pages auto reload incredibly fast, it has everything that I need for editing my markdown files 

I wrote like 300 lines of markdown today, and I think this is the first time I enjoy the experience of writing markdown.

Thank you.

**Comment by commenthol** [comment]
Hi @zzyyxxww,
Thank you very much for your feedback. It's really appreciated.
Enjoy your markdown experience.
