### ISSUE TITLE
Can't add image md file (JPG, jpg, png)

### ISSUE THREAD

**Issue by gindev77** [commenthol/md-fileserver#15]
Hi, thank you to bring us this project!

I am able to run the server locally but i can't understand why it's not possible to add pictures like in any Markdown file....

The path i use look correct to me....

what  i am missing ?

thanks ...

example i use : 
``
![This is an image](/Assets/Images/img-14.PNG) 
``
i also tried absolute path ...

**Comment by commenthol** [comment]
Hi, 
`/Assets` is an absolute path pointing to the root directory. 
Please change the path to a relative path like `./Assets` then you'll see the image.
As I am unaware on the OS you are on. Maybe your filesystem is case-sensitive and your image is 
e.g. at `./assets/images/img-14.png`? Usually you can copy a path from explorer/ finder.

**Comment by gindev77** [comment]
Ok, thanks it's working,  i used a specific folder where i placed my md files. maybe this is why it wouldn't worked.
