### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by joaorebelo-ar** [commenthol/md-fileserver#2]
Hey,

Would it be possible to explain the manual installation without npm?

Thanks.

**Comment by commenthol** [comment]
Installing without npm is not possible with this project as it relies on other packages.

So I am referring to installing from a git clone here:

Assuming you have "git" and "node" which comes bundled with "npm" on your computer

```
git clone --depth 5 https://github.com/commenthol/md-fileserver.git
cd md-fileserver
# to install `mdopen` `mdstart` globally run
npm install -g
```

now you are able to run `mdopen` from a terminal.

**Comment by joaorebelo-ar** [comment]
Thanks. I guess I will try to take my computer home an install it the correct way.
