### ISSUE TITLE
Opening file by name doesn't work

### ISSUE THREAD

**Issue by zplizzi** [commenthol/md-fileserver#6]
Running `mdstart myfile.md` doesn't seem to work - it doesn't produce any output, but doesn't terminate either. Regular `mdstart` by itself works and can open the file once I navigate to it.

Awesome tool by the way!

**Comment by commenthol** [comment]
Hi. Can you please tell me which OS you use? In case of Windows can you also tell me the terminal?

**Comment by zplizzi** [comment]
Mac 10.14.4

**Comment by commenthol** [comment]
Just checked on macos 10.14.4 and all is working. 
Please check that you can open an url from the terminal by typing `open http://duck.com` - this should open your default browser showing the page.

**Comment by zplizzi** [comment]
Hmm, that works, and now `mdstart myfile.md` works fine too. Not sure what was going on before. Anyways thanks for the help!

**Comment by zplizzi** [comment]
Ah, the issue only happens in tmux. `open http://duck.com` throws an error. Maybe you could also print the url to terminal for use in places that can't directly open a browser?

**Comment by commenthol** [comment]
Hi @zplizzi, Could you please try v1.4.1 which should print the url on error.

**Comment by zplizzi** [comment]
Unfortunately I can't reproduce the issue now, even in tmux. `open http://duck.com` works fine, as does `mdstart myfile.md`. Not sure what changed, sorry!

**Comment by commenthol** [comment]
ok, no problem.
