### ISSUE TITLE
GitHub/GitLab partly behaviour

### ISSUE THREAD

**Issue by GHNewbiee** [commenthol/md-fileserver#9]
Hi, I'd like to ask if, with this server, I can simulate the behaviour of GitHub/GitLab as regards only serving files and browsing them and **not** git operations at all.

To be more specific, I would like to avoid committing the structure of my project in GitHub/GitLab as regards `md` files (documentation) and other static assets (photos, screen records, etc) but I would like to know that layout will work fine, when I decide to commit it, without any change. Can I achieve that with md-fileserver?

**Comment by commenthol** [comment]
This project uses markdown-it parser plus markdown add-ons (only if you use them)  which is different to the ones used by github/lab. So if 100% render accuracy is your goal than you would need to use the parser implementations from there.

Please check `mdstart /cheatsheet` for reference.
